# Generated by Django 5.2.17 on 2026-09-25 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('additional_information', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=30)),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resumes.resume')),
            ],
            options={
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['job', 'status'], name='application_job_id_7836e3_idx'), models.Index(fields=['applicant', 'status'], name='application_applica_b6966f_idx')],
                'constraints': [models.UniqueConstraint(fields=('applicant', 'job'), name='unique_application_per_user_job')],
            },
        ),
    ]
