# Generated by Django 5.2.17 on 2026-09-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsreport',
            name='matched_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
