# Generated by Django 5.2.17 on 2026-10-01 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0002_atsreport_matched_keywords'),
        ('jobs', '0002_job_recruiter'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsreport',
            name='critical_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='atsreport',
            name='formatting_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='atsreport',
            name='formatting_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atsreport',
            name='improvement_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='atsreport',
            name='job_company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='atsreport',
            name='job_description_input',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atsreport',
            name='job_title_input',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='atsreport',
            name='line_improvements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='atsreport',
            name='projects_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atsreport',
            name='resume_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='atsreport',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='atsreport',
            name='section_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='atsreport',
            name='skills_categorized',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='atsreport',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ats_reports', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='atsreport',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ats_reports', to='resumes.resume'),
        ),
    ]
