# Generated by Django 5.2.17 on 2026-10-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0003_atsreport_critical_issues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsreport',
            name='category_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='atsreport',
            name='good_lines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='atsreport',
            name='jd_match_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='atsreport',
            name='overall_analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atsreport',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
