# Generated by Django 5.2.17 on 2026-10-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0004_atsreport_category_scores_atsreport_good_lines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsreport',
            name='issues_found',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
