# Generated by Django 5.2.17 on 2026-09-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='unverified', max_length=20),
        ),
    ]
