"""
Django settings for job_nest project.

Generated by 'django-admin startproject' using Django 5.2.17.
"""

from pathlib import Path
import os

from dotenv import load_dotenv
import dj_database_url


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env for local development.
# Render uses its own Environment Variables.
load_dotenv(BASE_DIR / ".env")


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-jobnest-development-key",
)


# ============================================================
# DEBUG
# ============================================================

DEBUG = os.environ.get("DEBUG", "False").lower() in (
    "true",
    "1",
    "t",
    "yes",
)


# ============================================================
# ALLOWED HOSTS
# ============================================================

render_hostname = os.environ.get("RENDER_EXTERNAL_HOSTNAME")

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "[::1]",
    "jobnest-5lvh.onrender.com",
]

if render_hostname:
    ALLOWED_HOSTS.append(render_hostname)

extra_hosts = os.environ.get("EXTRA_ALLOWED_HOSTS", "") or os.environ.get("ALLOWED_HOSTS", "")

if extra_hosts:
    ALLOWED_HOSTS.extend(
        host.strip()
        for host in extra_hosts.split(",")
        if host.strip()
    )

ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))


# ============================================================
# CSRF TRUSTED ORIGINS
# ============================================================

CSRF_TRUSTED_ORIGINS = [
    "https://jobnest-5lvh.onrender.com",
]

if render_hostname:
    CSRF_TRUSTED_ORIGINS.append(
        f"https://{render_hostname}"
    )

extra_csrf_origins = os.environ.get("EXTRA_CSRF_ORIGINS", "") or os.environ.get("CSRF_TRUSTED_ORIGINS", "")

if extra_csrf_origins:
    CSRF_TRUSTED_ORIGINS.extend(
        origin.strip()
        for origin in extra_csrf_origins.split(",")
        if origin.strip()
    )

CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # JobNest applications
    "adm",
    "companies",
    "jobs",
    "applications",
    "resumes",
    "ats",
    "dashboard",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # WhiteNoise for production static files
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# ROOT URL
# ============================================================

ROOT_URLCONF = "job_nest.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates",
        ],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "job_nest.wsgi.application"


# ============================================================
# DATABASE
# ============================================================

# Render PostgreSQL
#
# Render provides:
#
# DATABASE_URL
#
# Example:
# postgresql://username:password@hostname/database
#
# Local development can use:
# DB_NAME
# DB_USER
# DB_PASSWORD
# DB_HOST
# DB_PORT

DATABASE_URL = (
    os.environ.get("DATABASE_URL")
    or os.environ.get("INTERNAL_DATABASE_URL")
    or os.environ.get("EXTERNAL_DATABASE_URL")
    or os.environ.get("RENDER_DATABASE_URL")
    or os.environ.get("DB_URL")
)

if DATABASE_URL:
    DATABASE_URL = DATABASE_URL.strip().strip("'\"")
    # Enable SSL for remote databases (e.g. Render), disable for local testing
    is_local_db = "127.0.0.1" in DATABASE_URL or "localhost" in DATABASE_URL
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=not is_local_db,
        )
    }
else:
    # Detect if running in Render production without DATABASE_URL
    is_render = bool(
        os.environ.get("RENDER")
        or os.environ.get("RENDER_EXTERNAL_HOSTNAME")
    )
    if is_render and os.environ.get("DB_HOST", "127.0.0.1") in ("127.0.0.1", "localhost"):
        import sys
        print(
            "\n" + "=" * 70 + "\n"
            "CRITICAL: DATABASE_URL is not configured in Render Environment Variables!\n"
            "Render web services do not run a local PostgreSQL instance on 127.0.0.1.\n"
            "Please go to your Render Web Service > Environment tab and add:\n"
            "  Key:   DATABASE_URL\n"
            "  Value: (Paste your Render PostgreSQL database's Internal Database URL)\n"
            + "=" * 70 + "\n",
            file=sys.stderr,
        )

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "jobs"),
            "USER": os.environ.get("DB_USER", "postgres"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }

# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "/static/"


# Existing static folder
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Production static files folder
STATIC_ROOT = BASE_DIR / "staticfiles"


# Production-safe WhiteNoise storage
# Compresses static files (gzip & brotli) and prevents
# 'Missing staticfiles manifest entry' errors.
STORAGES = {
    "default": {
        "BACKEND": (
            "django.core.files.storage.FileSystemStorage"
        ),
    },

    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage."
            "CompressedStaticFilesStorage"
        ),
    },
}

WHITENOISE_MANIFEST_STRICT = False


# ============================================================
# MEDIA FILES
# ============================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)


# ============================================================
# LOGIN / LOGOUT
# ============================================================

LOGIN_URL = "login"

LOGIN_REDIRECT_URL = "home"

LOGOUT_REDIRECT_URL = "home"


# ============================================================
# SESSION CONFIGURATION
# ============================================================

# 2 weeks
SESSION_COOKIE_AGE = 1209600

# Keep session after browser closes
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Update session on every request
SESSION_SAVE_EVERY_REQUEST = True


# ============================================================
# HTTPS / PRODUCTION SECURITY
# ============================================================

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"

if not DEBUG:

    # Render is behind a proxy.
    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )

    # Secure cookies
    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True


# ============================================================
# EMAIL CONFIGURATION
# ============================================================

EMAIL_HOST = os.environ.get(
    "EMAIL_HOST",
    "",
)


EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)


EMAIL_PORT = int(
    os.environ.get(
        "EMAIL_PORT",
        "587",
    )
)


EMAIL_HOST_USER = os.environ.get(
    "EMAIL_HOST_USER",
    "",
)


EMAIL_HOST_PASSWORD = os.environ.get(
    "EMAIL_HOST_PASSWORD",
    "",
)


EMAIL_USE_TLS = (
    os.environ.get(
        "EMAIL_USE_TLS",
        "True",
    ).lower()
    == "true"
)


EMAIL_USE_SSL = (
    os.environ.get(
        "EMAIL_USE_SSL",
        "False",
    ).lower()
    == "true"
)


DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "JobNest <noreply@jobnest.com>",
)


# ============================================================
# PASSWORD RESET
# ============================================================

# Password reset link expires after 1 hour
PASSWORD_RESET_TIMEOUT = int(
    os.environ.get(
        "PASSWORD_RESET_TIMEOUT",
        "3600",
    )
)